dhDatabaseIp: "158.85.248.111"
dhDatabasePort: 8888
eureka:
 client:
  serviceUrl:
   defaultZone: http://dheurekaserver.cfapps.io/eureka/
 instance:
    preferIpAddress: true
    hostname: ${CF_INSTANCE_INTERNAL_IP:localhost}
    nonSecurePort: ${CF_INSTANCE_PORT:${PORT:${server.port:8761}}}
